{
    "name" : "Document Page - Binary",
    "version" : "0.1",
    "author" : "Justin Mangini",
    'category': 'Knowledge',
    "depends" : ['document_page_type'],
    "init_xml" : [],
    "demo_xml" : [],
    "description": "Adds binary attachment document type to the document control system.",
    'data': ['views/views.xml', 'data/data.xml'],
    'test': [],
    'installable': True,
    'auto_install': False,
    'certificate': '',
    'images': [''],
}
